"""empty message

Revision ID: 27fd824dc720
Revises: badceaabd9ea
Create Date: 2022-03-15 13:06:46.502930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27fd824dc720'
down_revision = 'badceaabd9ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('views', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'views')
    # ### end Alembic commands ###
